name: copy
on: [workflow_dispatch]
  

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'data'
        destination-github-username: 'antoninfaure'
        destination-repository-name: 'personal-website'
        user-email: action@github.com
        target-branch: test
        target-directory: 'static/assets/rss-trends/data'
